### PR TITLE
build system fix and upgrade

### PR DESCRIPTION
**Pull request by stefantalpalaru**
- don't delete "allocfail.sh" on `make clean`
- ran more recent versions of Autotools to regenerate build system files
- new ".gitignore" entries for configuration/build artefacts not relevant for Git

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
@googlebot I signed it!

**Comment by ianlancetaylor** [comment]
Thanks, but libbacktrace intentionally uses the same versions of the autotools that GCC uses, which are documented at https://gcc.gnu.org/install/prerequisites.html.

**Comment by stefantalpalaru** [comment]
Regenerated with Automake-1.15.1. The other tools match the GCC versions.

**Comment by stefantalpalaru** [comment]
Rebased on "master".

**Comment by cooljeanius** [comment]
> Rebased on "master".

Try again? There are merge conflicts.

**Comment by stefantalpalaru** [comment]
> Try again?

Why bother?

**Comment by cooljeanius** [comment]
> > Try again?
> 
> Why bother?

I mean, I think it's still worth doing...

**Comment by ianlancetaylor** [comment]
What changes are still worth doing?  This pull request seems obsolete, given my decision that we are sticking with the exact autoconf/automake/libtool versions that are used by the GCC repository.

**Comment by stefantalpalaru** [comment]
> my decision that we are sticking with the exact autoconf/automake/libtool versions that are used by the GCC repository

With "config.sub" and "config.guess" that were so ancient that they failed to work in all GitHub Actions images I was using, back in February 2020. This is what I had to do:

https://github.com/status-im/nim-libbacktrace/blob/6cbd913e48062aa7e319336d7c0d99541622152a/Makefile#L121-L122

> What changes are still worth doing? 

Why bother? You're half-arsing it and you know it. How many years did it take you to merge macOS support? How many more until you make it work in Windows?

At least be honest and disable issues and PRs from this project's settings.

**Comment by ianlancetaylor** [comment]
Why be rude when you can be polite?  What do you gain by that?

libbacktrace is not high on my lengthy priority list, it's not a critical component of any software program (I hope), and it's not like anybody pays me to work on it.

I don't plan to disable issues or PRs on the repo.  I do look at them from time to time.

To the best of my knowledge libbacktrace already works on Windows.  That said I personally don't have any Windows or macOS machines to test on.

Thanks for the feedback.

**Comment by stefantalpalaru** [comment]
> it's not a critical component of any software program (I hope)

https://github.com/search?q=libbacktrace&type=code

**Comment by ianlancetaylor** [comment]
Understood, but libbacktrace is normally used on the error path to provide additional information, rather than on the correct execution path.  Additional information is of course useful but it's rarely critical.

**Comment by ianlancetaylor** [comment]
I just checked, and the config.guess and config.sub files are up to date with the GCC configury.  I updated them in the libbacktrace repo in January 2022 for #84.

**Pull request closed without merging**
