### PR TITLE
minidebuginfo support for elf

### PR DESCRIPTION
**Pull request by sargarass**
Hello, I added a minidebuginfo support for elf. Please take a look.
[Here](https://github.com/sargarass/libbacktrace-example) is a small example of usage with boost/stacktrace that used library as backend ( 6mb version of boost included ;) )

Also I had to create few wrappers for functions like backtrace_get_view, backtrace_release_view to accept not only filedescriptors but also already mapped to memory elf. Could go with memfd_create and just open uncompressed elf file but seems like it appered in linux 3.17.
For now the wrappers just copy any part that was asked to be viewed from uncompressed to memory elf file.

### CODE REVIEW

**Comment by ianlancetaylor** [comment]
Thanks, but libbacktrace must be async-signal-safe.  It's hard to be confident that that is true of an external library.  On my system, liblzma is compiled with `-fstack-check`, which is good in general but not a good idea for async-signal-safe code.  It also has references to `malloc`, even though it won't be called, which is troubling for a library as low-level as libbacktrace.  In general I think libbacktrace will need to include an LZMA decoder, just as it already has a zlib decoder.

**Comment by sargarass** [comment]
liblzma uses user's provided allocators for memory allocation (I used wrappers for backtrace_alloc/free). In case NULL was passed it goes back to malloc & free, so i think it is the reason why does it have references to malloc. Also libunwind uses lzma like this, but maybe they dont care that much about async-safety.

Anyway will consider includion lzma decoder into. Maybe it will be easy to port it directly from liblzma.

**Comment by sargarass** [comment]
@ianlancetaylor what do you think about using [XZ Embedded](https://tukaani.org/xz/embedded.html) which is used directly in the [Linux kernel](https://github.com/torvalds/linux/tree/master/lib/xz)? It is relatively small implementation with only decompression support. It could be included as a subdirectory to libbacktrace.

**Comment by ianlancetaylor** [comment]
Honestly my inclination is to just add a LZMA decoder like the existing zlib decoder.

**Comment by sargarass** [comment]
@ianlancetaylor hello. Has it become better? I used the xz embedded source code and mentioned both autors. Dropped redundant macroes, fixed codestyle (I hope I did), dropped single-call & preallocated modes. Everything now lives in elf.c file, so no externdependancies.I would like to believe that what you wanted?

**Comment by ianlancetaylor** [comment]
Thanks for sending this.  I went in a different direction by writing a simpler and smaller version of the LZMA decoder that knows that all the data is in memory.  It also doesn't use the BCJ decompressors, which should never be needed in minidebug info.  The new code is in 77bcaa99f5d1a8a4fabfca665f60a1739c5d024b.  Thanks again.

**Comment by sargarass** [comment]
Thank you, @ianlancetaylor. Sounds great, I'll try it at work, where we did use this branch for a while.

**Pull request closed without merging**
