### PR TITLE
Fix a typo: passd -> passed

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Review by krlmlr — APPROVED** [review]

**Comment by ianlancetaylor** [comment]
Thanks.  I committed this to the upstream sources and merged back into these sources.

**Comment by certik** [comment]
@ianlancetaylor thanks. Where is the upstream of this repository? Is it in GCC?

**Comment by ianlancetaylor** [comment]
Yes.  https://gcc.gnu.org/git/?p=gcc.git;a=tree;f=libbacktrace .

**Comment by certik** [comment]
Ah, cool, thanks for the link!

**Pull request closed without merging**
