### PR TITLE
Update config.guess and config.sub

### PR DESCRIPTION
**Pull request by shenki**
This syncs these files with the latest upstream versions. This is required to build libbacktrace on ppc64le.

### CODE REVIEW

**Comment by rustyrussell** [comment]
+1

**Comment by jsarenik** [comment]
Oops, excuse me for not noticing this.

**Comment by jsarenik** [comment]
https://github.com/ElementsProject/lightning/pull/1533

**Comment by ianlancetaylor** [comment]
Thanks.  I copied the current GCC versions of these files instead, to maintain consistency with the GCC sources.  That should be sufficient to work on ppc64le.

**Comment by jsarenik** [comment]
Thanks. I just found yesterday that older versions, even from this year, do not solve my problem on Alpine Linux (Musl-libc based).

**Comment by ianlancetaylor** [comment]
OK, I updated to the newest versions from the master repo.

**Comment by jsarenik** [comment]
Thank you!!!

**Comment by jsarenik** [comment]
Just a note that native Musl compilation worked but there were issues with cross-compilation. Thanks!

**Pull request closed without merging**
