### PR TITLE
libbacktrace: correct preprocessor directive for Windows lean definition

### LINKED ISSUE #144: WIN32_MEAN_AND_LEAN should be WIN32_LEAN_AND_MEAN
There are some files that have this: 

#ifdef HAVE_WINDOWS_H
#ifndef WIN32_MEAN_AND_LEAN
#define WIN32_MEAN_AND_LEAN
#endif

But I believe it should be:

#ifdef HAVE_WINDOWS_H
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

ref: Windows.h and https://learn.microsoft.com/en-us/windows/win32/winprog/using-the-windows-headers#faster-builds-with-smaller-header-files

### PR DESCRIPTION
**Pull request by awmorgan**
Fixes #144

### CODE REVIEW

**Comment by ianlancetaylor** [comment]
Thanks for pointing this out and sending the patch.  Committed upstream and merged back to this repo.

**Comment by awmorgan** [comment]
> Thanks for pointing this out and sending the patch. Committed upstream and merged back to this repo.

Where is upstream?

**Comment by ianlancetaylor** [comment]
The GCC repository.  See https://gcc.gnu.org/git.html.  The libbacktrace directory.

**Comment by ianlancetaylor** [comment]
The GCC repository.  See https://gcc.gnu.org/git.html.  The libbacktrace directory.

**Pull request closed without merging**
